// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDIhrHfOdh7stl2iyLdUk40mZjT92op6M',
    appId: '1:725885160754:web:6bc2ada1ef7e1a7625db2b',
    messagingSenderId: '725885160754',
    projectId: 'smartclassroom-3c967',
    authDomain: 'smartclassroom-3c967.firebaseapp.com',
    storageBucket: 'smartclassroom-3c967.firebasestorage.app',
    measurementId: 'G-WLYFHKY9KQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvlif4pGPWkRmwCYwNIRcLXG1x9HqER-I',
    appId: '1:725885160754:android:8c31e892cd656cc625db2b',
    messagingSenderId: '725885160754',
    projectId: 'smartclassroom-3c967',
    storageBucket: 'smartclassroom-3c967.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOaAz42vPWoSDCWxTIX5fGvBouFvZ5TN8',
    appId: '1:725885160754:ios:9f85f03f07b8f86025db2b',
    messagingSenderId: '725885160754',
    projectId: 'smartclassroom-3c967',
    storageBucket: 'smartclassroom-3c967.firebasestorage.app',
    iosBundleId: 'com.example.smartClassroom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOaAz42vPWoSDCWxTIX5fGvBouFvZ5TN8',
    appId: '1:725885160754:ios:9f85f03f07b8f86025db2b',
    messagingSenderId: '725885160754',
    projectId: 'smartclassroom-3c967',
    storageBucket: 'smartclassroom-3c967.firebasestorage.app',
    iosBundleId: 'com.example.smartClassroom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDIhrHfOdh7stl2iyLdUk40mZjT92op6M',
    appId: '1:725885160754:web:cd842123aafa014125db2b',
    messagingSenderId: '725885160754',
    projectId: 'smartclassroom-3c967',
    authDomain: 'smartclassroom-3c967.firebaseapp.com',
    storageBucket: 'smartclassroom-3c967.firebasestorage.app',
    measurementId: 'G-0LE27CHPK1',
  );

}