// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4af7VMRZaJuHeF7mVxY4L65CucEAPSoE',
    appId: '1:324497999858:web:d51470f745ca5266aa8d6b',
    messagingSenderId: '324497999858',
    projectId: 'flutter-firebase-app-a7f68',
    authDomain: 'flutter-firebase-app-a7f68.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-a7f68.firebasestorage.app',
    measurementId: 'G-94XYLGDN4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgIIz-sPSgexgEV93HOkFwArg18P0rdM0',
    appId: '1:324497999858:android:96dc125c6fb778bdaa8d6b',
    messagingSenderId: '324497999858',
    projectId: 'flutter-firebase-app-a7f68',
    storageBucket: 'flutter-firebase-app-a7f68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARUnTKneTIPQKxV6SyLisWuiW9gz6e08Y',
    appId: '1:324497999858:ios:19681cb0fb6fe3c4aa8d6b',
    messagingSenderId: '324497999858',
    projectId: 'flutter-firebase-app-a7f68',
    storageBucket: 'flutter-firebase-app-a7f68.firebasestorage.app',
    iosBundleId: 'com.example.smartClassroom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARUnTKneTIPQKxV6SyLisWuiW9gz6e08Y',
    appId: '1:324497999858:ios:19681cb0fb6fe3c4aa8d6b',
    messagingSenderId: '324497999858',
    projectId: 'flutter-firebase-app-a7f68',
    storageBucket: 'flutter-firebase-app-a7f68.firebasestorage.app',
    iosBundleId: 'com.example.smartClassroom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4af7VMRZaJuHeF7mVxY4L65CucEAPSoE',
    appId: '1:324497999858:web:0484786627752941aa8d6b',
    messagingSenderId: '324497999858',
    projectId: 'flutter-firebase-app-a7f68',
    authDomain: 'flutter-firebase-app-a7f68.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-a7f68.firebasestorage.app',
    measurementId: 'G-SVXZ7PJP5N',
  );
}
